### ISSUE TITLE
Create Race Class

### ISSUE THREAD

**Issue by Grandmagic13** [Grandmagic13/RPGManager#56]
- Create a class for Races
- Refactor functionality that works simpler using Races

**Comment by Pluci** [comment]
- It calculating either from the chosen background, or if you choose first a race you can select from a lesser background list, depends on the selected race.

**Comment by Grandmagic13** [comment]
Race selection has to be transparent to the user and done automatically through Background selection. This can be achieved in a variety of different ways, like
- Background class setting a field in the characterSheet for RACE, or
- Background containing an enum field called race, which is gettable and is decided on static initialization

If race is refactored, certain pre-existing parameterized tests, such as the ones testing Specialization Background restrictions may have to be refactored or modified. Regardless of the tests, the source code for background restrictions can be and should be simplified if this functionality has been implemented.
